cors:
    url: '*'
logging:
    level:
        org:
            springframework:
                boot:
                    autoconfigure: ERROR
            hibernate: DEBUG
            hibernate.SQL: debug
        root: TRACE
        sql: TRACE
        web: DEBUG
server:
    address: localhost
    port: 8080
    servlet:
        contextPath: /
spring:
    datasource:
        url: jdbc:sqlite:/Users/hugoscavino/Development/sqlite-tools-osx-x64-3440200/searchforarace.db
        driver-class-name: org.sqlite.JDBC
    jpa:
        database-platform: org.hibernate.community.dialect.SQLiteDialect
        open-in-view: true
        properties:
            hibernate:
                format_sql: true
                show_sql: true
                temp:
                    use_jdbc_metadata_defaults: false
        show-sql: true
