INSERT INTO races (id, name, date, description, address_id, url, public, coupon_code, author_id, mod_date, active, cancelled) VALUES (2, 'Jacksonville Half & Full Marathon', '2023-12-10 00:00:00', 'Oldest marathon in Jacksonville, Florida', 3, 'https://www.amerisbank.com/jacksonville-marathon/', true, '', 0, '2019-09-07 22:17:19', true, false);
INSERT INTO races (id, name, date, description, address_id, url, public, coupon_code, author_id, mod_date, active, cancelled) VALUES (3, 'Challenge Daytona 70.3', '2023-12-01 00:00:00', 'Challenge this! Swim, bike, and run at Daytona International Speedway, the iconic World Center of Racing', 4, 'http://challenge-daytona.com/', true, '', 0, '2019-09-07 22:17:01', true, false);
INSERT INTO races (id, name, date, description, address_id, url, public, coupon_code, author_id, mod_date, active, cancelled) VALUES (4, 'Ironman Chattanooga 70.3', '2023-09-24 00:00:00', 'Race Sunbelt Bakery IRONMAN 70.3 Chattanooga', 5, 'http://www.ironman.com/triathlon/events/americas/ironman-70.3/chattanooga.aspx#/axzz5TfxBtRM7', true, '', 0, '2019-09-07 22:27:00', true, false);
INSERT INTO races (id, name, date, description, address_id, url, public, coupon_code, author_id, mod_date, active, cancelled) VALUES (6, 'Ironman Florida 140.6', '2023-11-04 00:00:00', 'Changed to Haines City', 28, 'http://www.ironman.com/triathlon/events/americas/ironman/florida.aspx', true, '', 0, '2019-09-07 22:16:07', true, false);
INSERT INTO races (id, name, date, description, address_id, url, public, coupon_code, author_id, mod_date, active, cancelled) VALUES (7, 'Chicago Marathon', '2023-10-08 00:00:00', 'Grand Ave, Chicago IL', 9, 'https://www.chicagomarathon.com/', true, '', 0, '2019-09-07 22:28:54', true, false);
INSERT INTO races (id, name, date, description, address_id, url, public, coupon_code, author_id, mod_date, active, cancelled) VALUES (9, 'Wiregrass Turkey Trot', '2023-11-23 00:00:00', 'Wiregrass Mall', 11, 'http://www.wiregrasswobbleturkeytrot.com/', true, '', 0, '2019-09-07 22:16:45', true, false);
INSERT INTO races (id, name, date, description, address_id, url, public, coupon_code, author_id, mod_date, active, cancelled) VALUES
                (12, 'St. Anthony''s Triathlon', '2024-04-26 00:00:00', 'St. Petersburg Fl - Vinoy Park', 14,
                 'https://baycare.org/satriathlon', true, '', 0, '2019-10-01 23:49:23', true, false);
INSERT INTO races (id, name, date, description, address_id, url, public, coupon_code, author_id, mod_date, active, cancelled) VALUES (16, 'Mt. Dora Half Marathon', '2023-12-16 00:00:00', 'Hilly Race', 17, 'http://www.mountdorahalfmarathon.com/', true, '', 0, '2019-09-07 22:17:37', true, false);
INSERT INTO races (id, name, date, description, address_id, url, public, coupon_code, author_id, mod_date, active, cancelled) VALUES (19, 'Celebration Half & Full Marathon', '2024-01-28 00:00:00', 'Celebration, FL', 20, 'https://www.celebrationmarathon.com/', true, '', 0, '2019-09-07 22:19:48', true, false);
INSERT INTO races (id, name, date, description, address_id, url, public, coupon_code, author_id, mod_date, active, cancelled) VALUES (21, 'Gasparilla Running Festival', '2024-02-24 00:00:00', 'Has challenged athletes, brought people together for a fun, exciting weekend, and raised funds for charitable youth organizations and running programs in the Tampa Bay area', 22, 'http://www.publix.com/gasparilla', true, '', 0, '2019-09-07 22:22:01', true, false);
INSERT INTO races (id, name, date, description, address_id, url, public, coupon_code, author_id, mod_date, active, cancelled) VALUES (27, 'IRONMAN 70.3 AUGUSTA', '2023-09-24 00:00:00', 'Steeped in American history, this popular Southern race features a down-current swim.', 30, 'http://www.ironman.com/triathlon/events/americas/ironman-70.3/augusta.aspx', true, '', 0, '2019-09-07 22:28:45', true, false);
INSERT INTO races (id, name, date, description, address_id, url, public, coupon_code, author_id, mod_date, active, cancelled) VALUES (227, 'IRONMAN 70.3 Puerto Rico', '2024-03-17 00:00:00', 'Old San Juan is like a museum of living history, where you can explore the impressive San Felipe del Morro and San Cristóbal castles or just wander through the cobblestone streets and soak up the unique architecture of the city. The triathlon community here provides remarkable support at this best-loved event. ', 205, 'https://www.ironman.com/im703-puerto-rico', true, NULL, 3, '2020-01-04 04:32:21.451727', true, true);
INSERT INTO races (id, name, date, description, address_id, url, public, coupon_code, author_id, mod_date, active, cancelled) VALUES (230, 'IRONMAN TEXAS 140.6 (Woodlasnds)', '2024-04-27 00:00:00', 'The 10th anniversary celebration of IRONMAN Texas in 2020 will be like no other. Athletes can expect a louder spectator-lined course, a grand 10th anniversary medal, and a bigger post-race celebration. Time and time again, athletes and spectators experience a one-of-a-kind event only the Lone Star State knows how to host.', 83, 'https://www.ironman.com/im-texas', true, NULL, 3, '2020-01-04 04:37:13.412132', true, false);
-- 2024
