INSERT INTO ournextrace.races VALUES (2, 'Jacksonville Half & Full Marathon', '2018-12-15 00:00:00', 'Oldest marathon in Jacksonville, Florida', 3, 'https://www.amerisbank.com/jacksonville-marathon/', true, '', 0, '2019-09-07 22:17:19', true);
INSERT INTO ournextrace.races VALUES (3, 'Challenge Daytona 70.3', '2018-12-09 00:00:00', 'Challenge this! Swim, bike, and run at Daytona International Speedway, the iconic World Center of Racing', 4, 'http://challenge-daytona.com/', true, '', 0, '2019-09-07 22:17:01', true);
INSERT INTO ournextrace.races VALUES (4, 'Ironman Chattanooga 70.3', '2019-05-19 00:00:00', 'Race Sunbelt Bakery IRONMAN 70.3 Chattanooga', 5, 'http://www.ironman.com/triathlon/events/americas/ironman-70.3/chattanooga.aspx#/axzz5TfxBtRM7', true, '', 0, '2019-09-07 22:27:00', true);
INSERT INTO ournextrace.races VALUES (5, 'Space Coast Half & Full Marathon', '2018-11-25 00:00:00', 'Blasting off in Cocoa Beach, FL', 6, 'https://www.spacecoastmarathon.com/', true, '', 0, '2019-09-07 22:16:53', true);
INSERT INTO ournextrace.races VALUES (6, 'Ironman Florida 140.6', '2018-11-04 00:00:00', 'Changed to Haines City', 28, 'http://www.ironman.com/triathlon/events/americas/ironman/florida.aspx', true, '', 0, '2019-09-07 22:16:07', true);
INSERT INTO ournextrace.races VALUES (7, 'Chicago Marathon', '2019-10-06 00:00:00', 'Grand Ave, Chicago IL', 9, 'https://www.chicagomarathon.com/', true, '', 0, '2019-09-07 22:28:54', true);
INSERT INTO ournextrace.races VALUES (8, 'Tampa Bay Times Turkey Trot', '2018-11-22 00:00:00', 'Clearwater High School', 10, 'https://www.tampabay.com/marketing/turkey-trot/', true, '', 0, '2019-09-07 22:16:30', true);
INSERT INTO ournextrace.races VALUES (9, 'Wiregrass Turkey Trot', '2018-11-22 00:00:00', 'Wiregrass Mall', 11, 'http://www.wiregrasswobbleturkeytrot.com/', true, '', 0, '2019-09-07 22:16:45', true);
INSERT INTO ournextrace.races VALUES (10, 'HITS Sarasota', '2019-01-06 00:00:00', 'Sarasota, FL - Nathan Benderson Park i', 12, 'http://hitstriathlonseries.com/sarasota-fl/', true, '', 0, '2019-09-07 22:17:56', true);
INSERT INTO ournextrace.races VALUES (11, 'HITS Ocala', '2019-03-30 00:00:00', 'Ocala, FL - Carney Island Park', 13, 'http://hitstriathlonseries.com/ocala-fl/', true, '', 0, '2019-09-07 22:25:23', true);
INSERT INTO ournextrace.races VALUES (12, 'St. Anthony''s Triathlon', '2019-04-28 00:00:00', 'St. Petersburg Fl - Vinoy Park', 14, 'https://baycare.org/satriathlon', true, '', 0, '2019-10-01 23:49:23', true);
INSERT INTO ournextrace.races VALUES (14, 'Red Ribbon Half Marathon', '2018-11-09 00:00:00', 'Located in Central Florida, it also features a kids fun run and a 5K, there is something for the entire family!', 15, 'http://www.redribbonhalf.com/', true, '', 0, '2019-09-07 22:16:11', true);
INSERT INTO ournextrace.races VALUES (15, 'St. Pete Half Maraton', '2018-11-17 00:00:00', 'St. Pete Run Fest is three days of festival fun, including running events, The Rollin’ Oats Wellness Market and Cafe, local food, music and craft beer from 3 Daughters Brewing. With distances for kids, beginners and seasoned runners, there’s plenty to entertain the entire family in the Sunshine City, St. Petersburg, Florida.', 16, 'https://stpeterunfest.org/', true, '', 0, '2019-09-07 22:16:17', true);
INSERT INTO ournextrace.races VALUES (16, 'Mt. Dora Half Marathon', '2018-12-16 00:00:00', 'Hilly Race', 17, 'http://www.mountdorahalfmarathon.com/', true, '', 0, '2019-09-07 22:17:37', true);
INSERT INTO ournextrace.races VALUES (17, 'Best Damn Race Jacksonville', '2019-01-12 00:00:00', 'a running series created for runners by runners. Our goal is to provide a big race experience at a local race price', 18, 'https://jacksonville.bestdamnrace.com/', true, '', 0, '2019-09-07 22:18:03', true);
INSERT INTO ournextrace.races VALUES (18, 'Clearwater Half Marathon', '2019-01-20 00:00:00', 'challenging half marathon in Florida, with two ascents each over two relatively tall bridges connecting Clearwater to the barrier islands.', 19, 'http://clearwaterdistanceclassic.com/half-marathon/', true, '', 0, '2019-09-07 22:18:38', true);
INSERT INTO ournextrace.races VALUES (19, 'Celebration Half & Full Marathon', '2019-01-27 00:00:00', 'Celebration, FL', 20, 'https://www.celebrationmarathon.com/', true, '', 0, '2019-09-07 22:19:48', true);
INSERT INTO ournextrace.races VALUES (20, 'Sarasota Music Half Marathon', '2019-02-03 00:00:00', 'Enter Sarasota’s most exciting race…the 5th annual Metro Diner Sarasota Music Half Marathon & Rockin'' 10k. ', 21, 'http://www.sarasotahalf.com/', true, '', 0, '2019-09-07 22:20:23', true);
INSERT INTO ournextrace.races VALUES (21, 'Gasparilla Running Festival', '2019-02-23 00:00:00', 'Has challenged athletes, brought people together for a fun, exciting weekend, and raised funds for charitable youth organizations and running programs in the Tampa Bay area', 22, 'http://www.publix.com/gasparilla', true, '', 0, '2019-09-07 22:22:01', true);
INSERT INTO ournextrace.races VALUES (22, 'Sunshine Skyway 10K', '2019-03-03 05:00:00', 'The 2018 Inaugural Sunshine Skyway 10K Bridge Run raised $560,000 for the Armed Forces Families Foundation! One hundred percent of every registration fee dollar goes to fund projects that support the families of our service members.', 23, 'https://www.skyway10k.com/', true, '', 0, '2019-09-28 18:00:00', true);
INSERT INTO ournextrace.races VALUES (23, 'Gate River Run', '2019-03-10 00:00:00', '20,000 runners and largest 15K in USA', 24, 'http://www.1stplacesports.com/grr_index.html', true, '', 0, '2019-09-07 22:23:03', true);
INSERT INTO ournextrace.races VALUES (24, 'Great West Chase', '2018-10-27 00:00:00', 'The Great West Chase is a USATF/RRTC nationally certified 10K Run (Certification Code FL14089EBM), 5K Run/Walk (Certification Code FL-14088EBM) and Fun Run.', 27, 'http://www.greatwestchase.com/', true, '', 0, '2019-09-07 22:15:47', true);
INSERT INTO ournextrace.races VALUES (25, 'Ironman Texas 70.3', '2019-04-07 00:00:00', 'A flat, fast course that runs along southern Texas'' Gulf of Mexico coastline.', 29, 'http://www.ironman.com/triathlon/events/americas/ironman-70.3/texas.aspx', true, '', 0, '2019-09-07 22:25:34', true);
INSERT INTO ournextrace.races VALUES (26, 'Space Coast Half & Full Marathon', '2019-12-01 00:00:00', 'Blasting off in Cocoa Beach, FL', 6, 'https://www.spacecoastmarathon.com/', true, '', 0, '2019-09-07 22:29:17', true);
INSERT INTO ournextrace.races VALUES (27, 'IRONMAN 70.3 AUGUSTA', '2019-09-29 00:00:00', 'Steeped in American history, this popular Southern race features a down-current swim.', 30, 'http://www.ironman.com/triathlon/events/americas/ironman-70.3/augusta.aspx', true, '', 0, '2019-09-07 22:28:45', true);
INSERT INTO ournextrace.races VALUES (28, 'HITS Sarasota', '2020-01-05 00:00:00', 'HITS Sarasota 2020', 12, 'http://hitstriathlonseries.com/sarasota-fl/', true, '', 0, '2019-09-07 22:29:39', true);
INSERT INTO ournextrace.races VALUES (29, 'Running for the Bulls 5K Donut Dash', '2019-03-02 00:00:00', 'The Sigma Alpha Epsilon Fraternity at the University of South Florida (“USF”) presents RUNNING FOR THE BULLS 5K DONUT DASH at the Tampa Campus of the University of South Florida', 31, 'https://runsignup.com/Race/FL/Tampa/RunningWithTheBullsDonutDash5K', true, '', 0, '2019-10-02 00:58:45', true);
INSERT INTO ournextrace.races VALUES (30, 'Masters SCY Valentine''s Meet(Saturday)', '2019-02-09 00:00:00', 'This meet will be using 8 of the facility’s 20 short course yard lanes with Daktronics timing for competition and 10 lanes will be provided for warm-ups during the course of the meet. All events will be swum in numerical order slow to fast. ', 32, 'https://www.clubassistant.com/club/meet_information.cfm?c=1855&smid=11262', true, '', 0, '2019-10-06 18:00:00', true);
INSERT INTO ournextrace.races VALUES (31, 'St. Petersburg Distance Classic', '2019-02-10 00:00:00', 'With four competitive timed races from 3.1 to 26.2 miles, we have something for everyone during a winter weekend on Florida''s beautiful gulf coast, and so we invite athletes of all abilities to join us at the St. Petersburg Distance Classic.', 33, 'https://www.active.com/st-petersburg-fl/running/distance-running-races/inaugural-st-petersburg-distance-classic-2019', true, '', 0, '2019-09-07 22:21:11', true);
INSERT INTO ournextrace.races VALUES (32, 'Downtown Dunedin Half Marathon', '2019-01-19 00:00:00', 'Friends join us in this annual celebration of the Dunedin Half showcasing the most desirable town in the United States! This is a shady flat course along the completely flat and paved Pinellas County Fred Marquis Trail. You won''t find huge crowds and a congested course as each distance is limited to 200 participants and every registrant will receive the prized DUNEDIN Florida uniqe finisher''s medal.', 34, 'https://www.active.com/dunedin-fl/running/distance-running-races/the-downtown-dunedin-half-marathon-with-10k-and-5k-2019', true, '', 0, '2019-09-07 22:18:07', true);
INSERT INTO ournextrace.races VALUES (1, 'Zooma Florida Half Marathon', '2018-10-19 00:00:00', 'Zooma Florida was voted one of the top 20 half marathons AND top 20 for beautiful, on-course scenery', 2, 'http://zoomarun.com/race/florida/', true, '', 0, '2019-12-13 20:56:47.50327', true);
INSERT INTO ournextrace.races VALUES (33, 'Light Up the Night 5k', '2019-01-19 00:00:00', 'The mission of the Pasco Sheriff''s Office Light Up the Night Tampa Bay event is to bring awareness and education to all the surrounding areas of Tampa Bay about the perils of men, women, and children enslaved through the heinous acts of human trafficking', 35, 'https://lightupthenight.us/', true, '', 0, '2019-09-07 22:18:12', true);
INSERT INTO ournextrace.races VALUES (34, 'Running of the Bulls 5k', '2019-01-19 00:00:00', 'Be a part of this fantastic event and support a local high school! Runners and walkers of all paces are welcome! The Running of the Bulls 5k, an event put on by the Bloomingdale Band Boosters, will take place on the Bloomingdale High School campus, in Valrico, Florida. All proceeds go to Bloomingdale High School.', 36, 'https://fitniche.com/event/running-bulls-5k-2/', true, '', 0, '2019-09-07 22:18:16', true);
INSERT INTO ournextrace.races VALUES (35, 'DREAM Clearwater MLK Day 5K', '2019-01-19 00:00:00', 'On Monday, January 21, 2019, join us at 9 a.m. as we celebrate Martin Luther King Jr.  Day in this non competitive 5K walk/run recognizing The Clearwater MLK Jr. Neighborhood Center Coalition in Clearwater directed by Anthony Burney.', 37, 'https://www.active.com/clearwater-fl/running/distance-running-races/the-dream-clearwater-mlk-day-5k-on-memorial-causeway-2019', true, '', 0, '2019-09-07 22:18:23', true);
INSERT INTO ournextrace.races VALUES (36, 'Countryside Country Club''s - Run In The New Year', '2019-01-26 00:00:00', 'RACES WILL BE RUN ON THE CART PATHS OF COUNTRYSIDE’S “PINE” & “LAKE” GOLF COURSE', 38, 'https://www.active.com/clearwater-fl/running/distance-running/countryside-country-club-s-run-in-the-new-year-2019', true, '', 0, '2019-10-12 18:00:00', true);
INSERT INTO ournextrace.races VALUES (37, 'JOSHUA 1:9 FREEDOM 5K RUN/WALK', '2019-01-26 00:00:00', 'Milliatary, Veterans and First Reponders only pay $20', 39, 'https://runsignup.com/Race/FL/Ruskin/Joshua19Freedom5KRunWalk', true, '', 0, '2019-09-07 22:19:07', true);
INSERT INTO ournextrace.races VALUES (38, 'Run For Life 5k', '2019-01-26 00:00:00', 'Run For Life, a community event to benefit the non-profit Zephyrhills Pregnancy Care Center, which annually helps hundreds of moms and their children in desperate situations in our community, is scheduled for January 26, 2019.  This event will begin on 5th Ave., near the Main Street Stage; race day registration begins at 7 a.m.; 5k starts at 8:30; 1 mi. Fun Run starts at 9:15.  Everyone is invited to be a part of this event.  There will be a music set and last chance donation for the Pregnancy Care Center, and of course refreshments for participants. Trophies and medals will go to top finishers. There will be a chance for some giveaways for registered participants. ', 40, 'https://www.active.com/zephyrhills-fl/running/distance-running-races/run-for-life-5k-and-1-mi-2019', true, '', 0, '2019-09-07 22:19:18', true);
INSERT INTO ournextrace.races VALUES (39, 'Clearwater Running Festival Presented by BJ''s Wholesale Club', '2019-01-27 00:00:00', 'Clearwater, situated on the Gulf of Mexico, has been named America’s #1 beach and is just 22 miles from Tampa on Florida’s stunning west coast. Clearwater boasts an endless supply of sun, warm weather, great dining and is a prime location for a running festival.', 19, 'https://www.active.com/clearwater-fl/running/distance-running-races/clearwater-running-festival-presented-by-bj-s-wholesale-club-2019?int=', true, '', 0, '2019-10-15 18:00:00', true);
INSERT INTO ournextrace.races VALUES (40, 'Florida Challenge  Trail Runs - Half Marathon', '2019-01-27 00:00:00', 'Half Marathon - The course will only be monitored for 3 1/2 hours. Only attempt the Half-Marathon if you think you can complete the race in that time.', 41, 'https://www.tamparaces.com/challenge/details.html', true, '', 0, '2019-09-07 22:19:33', true);
INSERT INTO ournextrace.races VALUES (41, 'Holloway Park Half Marathon & 5K', '2019-02-02 00:00:00', 'Holloway Park, a beautiful private 360 acre urban park full of natural habitat, oak trees and rolling grass meadows is conveniently located in Central Florida. The park is host to a multitude of elementary up to college age races throughout the fall. They are also host to a Race Series called the Run Wild Signature Race Series. Sign up for all of the races in the series to earn a plaque at the end of the series.', 42, 'https://www.athlinks.com/event/holloway-park-half-marathon-5k-130659', true, '', 0, '2019-09-07 22:19:59', true);
INSERT INTO ournextrace.races VALUES (42, 'METRO DINER  SARASOTA MUSIC HALF MARATHON', '2019-02-03 00:00:00', 'Enter Sarasota’s most exciting race…the 5th annual Metro Diner Sarasota Music Half Marathon & Rockin'' 10k.

A 13.1 and 6.2 mile moving party with thousands of your buddies:', 21, 'http://www.sarasotahalf.com/', true, '', 0, '2019-09-07 22:20:17', true);
INSERT INTO ournextrace.races VALUES (43, 'Rotary Twilight 5K', '2019-02-08 00:00:00', 'Join us for a scenic run around Lake Hollingsworth in Lakeland, Florida to benefit Common Ground Park – a park where children of varying abilities can explore and discover with imaginative play experiences. The four Rotary Clubs of Lakeland have worked together to support this park since its inception and proceeds from this annual race support the ongoing maintenance.', 44, 'http://rotary5k.net/', true, '', 0, '2019-09-07 22:20:31', true);
INSERT INTO ournextrace.races VALUES (44, 'Discover Caladesi Island 10 Mile Beach/Trail Race', '2019-02-09 00:00:00', '10 Mile Beach/Trail Run:The course will be out & back heading north from PIER 60 along Clearwater Beach to Caladesi Island, through trails on Caladesi Island & back, returning along the beach to PIER 60. Packet Pick Up is race day starting at 6:00 AM at Clearwater Beach Pier 60 Park.
Race start is 7:30 AM (rain or shine).', 45, 'https://www.signmeup.com/site/online-event-registration/128106', true, '', 0, '2019-10-20 18:00:00', true);
INSERT INTO ournextrace.races VALUES (45, 'Red Mule Runners Good Neighbor Trail 5K', '2019-02-09 00:00:00', '5th Annual Red Mule Runners Good Neighbor Trail 5k Run is back!!! Come join us on Brooksville''s finest paved trails shaded with old oak trees and beautiful scenery. Fast out and back course.  Finisher medals for all finishers!! Long sleeve shirts to all preregistered runners!!!', 46, 'https://www.active.com/brooksville-fl/running/mud-runs-races/5th-annual-red-mule-runners-good-neighbor-trail-5k-2019?int=', true, '', 0, '2019-10-21 18:00:00', true);
INSERT INTO ournextrace.races VALUES (46, 'Hunter’s Green 5K Music Fest', '2019-02-09 00:00:00', 'Run this scenic 5K course through the beautiful neighborhood and park of Hunter’s Green.  This race is chipped and officially timed by FitNiche Events.
The fun continues that evening with a live Music Fest from the stage at the Hunter’s Green Community Park. There will be bands performing from various genres, food trucks, silent auction tent, kid’s activities and lots more!  Register the whole family, we have something for everyone!', 47, 'http://huntersgreenpta.com/5k/', true, '', 0, '2019-10-22 18:00:00', true);
INSERT INTO ournextrace.races VALUES (47, 'SPC Titan Trot 5K 2019', '2019-02-09 00:00:00', 'The SPC Titan Trot is put on by the Faculty Governance Organization (FGO) as a way to raise scholarship money for our students.  Join us for an inclusive, fun 5K.

The race starts on the beautiful Clearwater Campus before heading down the trail to Cliff Stephens Park. ', 49, 'https://www.active.com/clearwater-fl/running/distance-running-races/spc-titan-trot-5k-2019', true, '', 0, '2019-10-23 18:00:00', true);
INSERT INTO ournextrace.races VALUES (48, 'Strawberry Distance Challenge', '2019-02-09 00:00:00', 'The course will close at 9:00am to open traffic for the neighborhood. Awards will begin at 9:00am. It is a 8-10 minute walk to the start line. Please allow enough time to get there.  Jarrett Scott Ford and Plant City Police department will lead the run. There will be a trail car and golf cart assistance as needed.', 50, 'http://strawberrydistancechallenge.com/', true, '', 0, '2019-09-07 22:20:50', true);
INSERT INTO ournextrace.races VALUES (49, 'The Super Run - Tampa 2019', '2019-02-09 00:00:00', 'The Super Run Caped Crusaders 5k is a superhero themed run where you become a real life superhero!  Grab your cape and fly over to The Super Run for a 5k fun run, music, festivities and more.  ', 52, 'https://www.active.com/tampa-fl/running/distance-running-races/the-super-run-tampa-fl-2019?int=', true, '', 0, '2019-10-25 18:00:00', true);
INSERT INTO ournextrace.races VALUES (67, 'Halo 5K', '2019-03-16 00:00:00', 'CHIP TIMING AWARDS & PRIZES DRY FIT SHIRT & MEDAL', 52, 'https://www.thehalo5k.com/race-info', true, '', 0, '2019-11-12 18:00:00', true);
INSERT INTO ournextrace.races VALUES (50, 'TROUT CREEK TRAIL RUNS 5K & 15K', '2019-02-10 00:00:00', 'Join us for the 14th Annual Trout Creek Trail Runs, held in the beautiful Trout Creek Wilderness Park in NE Hillsborough County. This course winds through pines, oak hammocks, and lakes using single track. You will also enjoy running on the elevated berm. ', 53, 'https://www.tamparaces.com/xterra-trout-creek-trail-runs-5k-15k/', true, '', 0, '2019-10-26 18:00:00', true);
INSERT INTO ournextrace.races VALUES (51, 'Tampa Bay Foundation for Mental Health 2nd Annual 5K Run/Walk for Wellness', '2019-02-10 00:00:00', 'The Tampa Bay Foundation for Mental Health focuses on community outreach, community partnerships and supporting community based programs that increase the mental health and awareness of our community. We believe that by improving community knowledge and understanding of mental health issues will lead to less stigma and negative perceptions of those suffering.', 54, 'https://www.eventbrite.com/e/tampa-bay-foundation-for-mental-health-2nd-annual-5k-runwalk-for-wellness-tickets-49069029789', true, '', 0, '2019-10-27 18:00:00', true);
INSERT INTO ournextrace.races VALUES (53, 'Bridge a Life Superhero 5K and Fun Run', '2019-02-16 00:00:00', 'More than just a race, the Superhero 5K brings together child welfare agencies and the community to highlight the nearly 1500 youth who are in local foster care in Sarasota, Manatee, and DeSoto Counties, while providing a family-friendly event with music, a kiddie zone, food, and giveaways.', 12, 'https://runsignup.com/Race/FL/Sarasota/BridgealifeSuperhero5KandFunRun', true, '', 0, '2019-10-29 18:00:00', true);
INSERT INTO ournextrace.races VALUES (54, 'Meals on Wheels 5K', '2019-02-16 00:00:00', 'Plenty of Parking and Food Trucks', 55, 'http://www.mowtampa.org/5K/', true, '', 0, '2019-10-30 18:00:00', true);
INSERT INTO ournextrace.races VALUES (55, 'Run 4 One 5K', '2019-02-16 00:00:00', 'Run4one is an annual family walk/run that raises funds for the rescue and rehabilitation of human trafficking victims.', 56, 'http://run4one5k.org/', true, '', 0, '2019-10-31 18:00:00', true);
INSERT INTO ournextrace.races VALUES (56, 'Tampa Bay Tequila Half Marathon With 10K and 5K Whiskey Joe''s Tampa', '2019-02-16 00:00:00', 'The Tampa Bay Tequila Half Marathon invites you to join us at Whiskey Joe''s Tampa on Saturday February 16, 2019. A different medal for each distance will make it a tough choice when you register! The half marathon runners each get the prize TEQUILA medal, 10K runners will receive the 10K Whiskey medal and 5K runners and walker all go home with the beer keg barrel finisher''s medal each photograph found at www.727CanRace.com  Whatever distance you choose you will be running WITH WATER ON BOTH SIDES! We hope you enjoy this race across the Bay!', 57, 'https://www.active.com/tampa-fl/running/distance-running-races/the-tampa-bay-tequila-half-marathon-with-10k-and-5k-whiskey-joe-s-tampa-2019?int=72-3-A5', true, '', 0, '2019-11-01 18:00:00', true);
INSERT INTO ournextrace.races VALUES (57, 'Light Up The Night 5k', '2019-03-01 00:00:00', 'The Junior League of Greater Winter Haven''s Light Up The Night 5k race winds through the beautiful downtown Winter Haven area and extends past Lake Silver onto the trail. Prior to the race beginning, a costume contest will be held for all costumed participants who would like to participate. The race concludes in the BB&T bank parking lot, where a post-race party complete with awards ceremony will occur at Grove Roots Brewery. This is the best after-dark race in Winter Haven.', 58, 'https://www.active.com/winter-haven-fl/running/distance-running/light-up-the-night-5k-run-2019?int=', true, '', 0, '2019-11-02 18:00:00', true);
INSERT INTO ournextrace.races VALUES (58, 'Isaac''s Run - 2019', '2019-02-02 00:00:00', 'This timed 5K run will be held on the Dade City (East) Campus of Pasco-Hernando State College. Overall, Masters, and Age Group awards will be presented.
Isaac Wetherington was born in October of 2010 with Hypoplastic Left Heart Syndrome to parents Jason and Stephanie Wetherington.  Tragically, after already enduring 3 open heart surgeries, Isaac, died in May of 2012 while in the CICU at Boston Children’s Hospital.', 35, 'https://www.raceentry.com/isaacs-run/race-information', true, '', 0, '2019-11-03 18:00:00', true);
INSERT INTO ournextrace.races VALUES (59, 'Run, Walk, and Roll 5k', '2019-03-02 00:00:00', 'The Student Accessibility Services Office at Pasco-Hernando State College is hosting a 5K race to benefit students with disabilities. All proceeds will directly support students who are in need of financial assistance to secure the appropriate documentation for academic accommodations. The funds will allow students access to the services and support that they need to succeed in college.', 35, 'https://www.active.com/wesley-chapel-fl/running/run-walk-and-roll-5k-2019?int=72-3-A4', true, '', 0, '2019-11-04 18:00:00', true);
INSERT INTO ournextrace.races VALUES (60, 'UA PTA Steps for Students 5K and Fun Run', '2019-03-02 00:00:00', 'This is a 5k and Kids Fun Run fundraiser held at Summerlin Park to benefit Union Academy. All participants will receive a free t-shirt and a morning of fun with friends!', 59, 'https://z-upload.facebook.com/events/358143641432980/', true, '', 0, '2019-11-05 18:00:00', true);
INSERT INTO ournextrace.races VALUES (61, 'Take Stock 5K', '2019-03-02 00:00:00', 'Take Stock in Children of Manatee County will hold the 10th Annual Take Stock 5k/Fun Run, Sunday, March 3, 2019. Runners will start and finish on Main Street in Lakewood Ranch. The 5k is scheduled to begin at 8:00 a.m. The Kids Run (ages 3-12) starts at 7:15 a.m. Post Race party with food, entertainment, awards and kids activities immediately following the race. ', 60, 'https://raceroster.com/events/2019/21376/2019-take-stock-5k', true, '', 0, '2019-11-06 18:00:00', true);
INSERT INTO ournextrace.races VALUES (62, 'Chasco Main Street Mile', '2019-03-30 00:00:00', 'The Chasco Main Street Mile is an exciting 1 mile race run 15 minutes before the Chasco Fiesta Parade. You will run in front of thousands spectators!', 61, 'https://runsignup.com/Race/FL/NewPortRichey/ChascoMainStreetMile', true, '', 0, '2019-11-07 18:00:00', true);
INSERT INTO ournextrace.races VALUES (63, 'Orange Blossom Half Marathon 5K', '2019-03-09 00:00:00', 'Join us in Haines City for a beautiful Half Marathon along country roads in one of the old citrus growing regions of Florida. Haines City is located midway between Orlando & Tampa. A 10K and 5K course is also available.  Approximately 4 miles of the half marathon course is on clay roads.', 28, 'https://runsignup.com/Race/FL/HainesCity/OrangeBlossomHalfMarathonand5K', true, '', 0, '2019-11-08 18:00:00', true);
INSERT INTO ournextrace.races VALUES (64, 'STARKEY WILDERNESS STOMP HALF MARATHON, 10K & 5K', '2019-03-09 00:00:00', 'Start Time: 8am
Course: Two loops of a mix of dirt hiking trails and just a little single track mountain bike trail. (but note this is not on the paved trails--it is on the dirt hiking trail)
Aid Stations: 2-3 on route with sports drink (each lap) and water. BUT, there will not be an aid station every mile.', 62, 'https://www.active.com/new-port-richey-fl/running/distance-running/starkey-wilderness-stomp-half-marathon-10k-and-5k-2019?int=72-3-A2', true, '', 0, '2019-11-09 18:00:00', true);
INSERT INTO ournextrace.races VALUES (65, 'WHPD 5k (for Special Olympics Florida)', '2019-03-09 00:00:00', 'Law enforcement has been involved in raising funds for the Special Olympics Florida by participating in annual Torch Runs throughout the state.  This event is a way for the public to become involved and support the mission of Special Olympics Florida.    ', 58, 'https://www.active.com/winter-haven-fl/running/distance-running-races/whpd-5k-for-special-olympics-florida-2019?int=', true, '', 0, '2019-11-10 18:00:00', true);
INSERT INTO ournextrace.races VALUES (66, 'Downtown Dunedin 2019 St. Patrick''s Day 5K And Street Party', '2019-03-16 00:00:00', 'Friends join us for the Annual St. Patrick’s Day 5K which in 2019 will be hosted in DOWNTOWN Dunedin on Saturday, March 16, 2019, in conjunction with the closed street party!! Our 5K run or walk will begin at 10 a.m. from Weaver Park so that it leads you directly into the downtown street party with your amazing DUNEDIN finisher''s medal.  We encourage you to wear your best green outfit where you enjoy a post race party like no other in the closed down streets of historic downtown Dunedin, FL USA.', 63, 'https://www.active.com/dunedin-fl/running/distance-running-races/the-downtown-dunedin-st-patrick-s-day-5k-and-street-party-2019?int=', true, '', 0, '2019-11-11 18:00:00', true);
INSERT INTO ournextrace.races VALUES (68, 'Florida Shamrock Halfathon & 5K Race', '2019-03-17 00:00:00', 'Get your green on and join us in celebrating the arrival of spring during our 10th Annual Florida Shamrock Halfathon & 5K Race (formerly Florida Beach Halfathon and 5K), at Fort De Soto Park, located near St. Petersburg on Florida''s beautiful west coast at the mouth of Tampa Bay.', 64, 'https://www.active.com/st-petersburg-fl/running/distance-running-races/10th-annual-florida-shamrock-halfathon-and-5k-race-2019?int=72-3-A8', true, '', 0, '2019-11-13 18:00:00', true);
INSERT INTO ournextrace.races VALUES (69, 'Leprechaun''s 5k, 10k, Challenge, and Kid''s Fun Run', '2019-03-17 00:00:00', 'The 5k route is a loop route. Runners will need to study the map to understand the route (There is an outer and an inner loop. Both loops must be completed.). Runner''s will have several hours to complete this race.', 52, 'https://runsignup.com/Race/Events/FL/Tampa/TheLeprechaunsRun5k', true, '', 0, '2019-11-14 18:00:00', true);
INSERT INTO ournextrace.races VALUES (70, 'Heroes Twilight Run St. Pete Honoring Law Enforcement And Fire Rescue 5K 10K and 1 Mile', '2019-03-22 00:00:00', 'Friends join us the evening of Friday, March 22, 2019, in St. Petersburg At Demens Landing Park in the amazing downtown St. Petersburg at Bayshore Drive and 2nd Avenue S. St. Petersburg, Florida 33701.', 65, 'https://www.active.com/st-petersburg-fl/running/distance-running-races/heroes-twilight-run-st-pete-honoring-law-enforcement-and-fire-rescue-5k-10k-and-1-mile-2019?int=', true, '', 0, '2019-11-15 18:00:00', true);
INSERT INTO ournextrace.races VALUES (71, 'Beer Belly 5K', '2019-03-23 00:00:00', 'Benefiting Meals on Wheels Plus of Manatee', 60, 'https://beer-belly5k.com/', true, '', 0, '2019-11-16 18:00:00', true);
INSERT INTO ournextrace.races VALUES (72, 'Nun Run 5K & 1 Mile Salesian Sprint', '2019-03-23 00:00:00', 'Welcome to the 2nd Annual 5K NUN RUN and SALESIAN SPRINT One Mile Fun Run both benefiting the Villa Madonna campus, which includes the Villa Madonna School and the Salesians Youth Center. Proceeds will be used for tuition and sports program assistance, school equipment and supplies, and campus and facilities maintenance.', 66, 'https://nunrun5k.racehawk.com/', true, '', 0, '2019-11-17 18:00:00', true);
INSERT INTO ournextrace.races VALUES (73, 'IOA CORPORATE 5K', '2019-03-28 00:00:00', 'This is Tampa Bay''s Largest Office Party! The IOA Corporate 5K is a one-of-a-kind fitness and social event designed to promote wellness within organizations, community and non-profit groups. Join in for a fun evening of fitness, networking, community pride, music, food, team camaraderie, entertainment and a whole lot more! Put your best foot forward in creating a happier and healthier workplace by registering your team today!', 67, 'https://events.hakuapp.com/ioa-corporate-5k-1', true, '', 0, '2019-11-18 18:00:00', true);
INSERT INTO ournextrace.races VALUES (74, '9 Mile War 15K/5K/1M Hill Challenge', '2019-03-30 00:00:00', 'Come join us for the 1st annual 9 Mile War 15K/5K/1M Hill Challenge on Saturday March 30th. Named after the fierce rivalry between Zephyrhills High School and Pasco HIgh School, this race will run in between Zephryrhills and Dade City on the brand new bike trail on the side of 301. It will start and finish at around the Jim Browne Chevrolet dealership on 301. If you are not familiar with the area, this race will feature some massive hills that will challenge even the best runners. Since this is a rivalry, you will have to choose sides when registering for the race. The side that gets the most runners will win the 9 Mile War trophy at the end. All proceeds will go to  Zephyrhills High School and Pasco High School''s Cross Country Teams and the Zephyrhills High School Athletic Booster Club. ', 68, 'https://runsignup.com/Race/FL/DadeCity/9MileWar15K', true, '', 0, '2019-11-19 18:00:00', true);
INSERT INTO ournextrace.races VALUES (75, 'Croom Trail 50 Mile, 50K, & 16 Mile Fool Run', '2019-03-30 00:00:00', 'The beautiful and challenging 50 mile course follows 3 repeat loops on the Croom Hiking Trail through central Florida’s long leaf pines and scrub oak covered hills, past creek bottoms and cypress ponds. There will be a 6:00pm cut off. The 50K race will follow the same course with 2 repeat loops and the 16 Mile Race is one loop. This is a wonderful course at a great time of the year for running - you don''t want to miss this race.', 69, 'http://www.fools50.com/index.html', true, '', 0, '2019-09-07 22:24:50', true);
INSERT INTO ournextrace.races VALUES (76, 'Lake Minneola Half Marathon, 12K and 5K', '2019-03-30 00:00:00', 'A beautiful run along the South Lake trail and for the half marathoner and 12K runners, a run around scenic Lake Minneola too!', 70, 'https://runsignup.com/Race/FL/Clermont/LakeMinneolaHalfMarathonand5K', true, '', 0, '2019-09-07 22:24:57', true);
INSERT INTO ournextrace.races VALUES (77, 'Positive Family Partners 5K', '2019-03-30 00:00:00', 'Positive Family Partners, promoting health and positive development for young children and families.
We provide and assist children, families, agencies, and our community with services and supports to promote positive development.
We assist the community to develop resources and expand service opportunities for children and families related to infant mental health and child and family health development.', 55, 'https://victorysportsmgt.com/event/pfp5k/', true, '', 0, '2019-11-22 18:00:00', true);
INSERT INTO ournextrace.races VALUES (78, 'Humana Iron Girl Clearwater', '2019-03-31 00:00:00', 'Half marathoners will enjoy a scenic run to the beach with a start and finish in Coachman Park.

The 5K course will travel over the causeway and turn back to finish in Coachman.

We’re excited to be part of your wellness journey.', 19, 'https://www.active.com/clearwater-fl/running/distance-running-races/humana-iron-girl-clearwater-2019', true, '', 0, '2019-09-07 22:25:28', true);
INSERT INTO ournextrace.races VALUES (79, 'River-N-Rapids Half Marathon, 10k & 5k', '2019-04-06 00:00:00', 'Now in it''s eigth year, the River-N-Rapids Half Marathon, 10k & 5k has grown into one of our most popular events--with trails to challenge you and one of the most scenic courses in the state.', 71, 'https://www.active.com/thonotosassa-fl/running/distance-running-races/river-n-rapids-half-marathon-10k-and-5k-2019?int=72-3-A7', true, '', 0, '2019-11-24 18:00:00', true);
INSERT INTO ournextrace.races VALUES (80, 'Chilly Willy Duathlon & 5K 2019', '2019-01-27 00:00:00', 'Welcome to the Chilly Willy Duathlon at beautiful Fort DeSoto park. This is the largest duathlon in the state of Florida and some of the best duathletes in all of southeastern United States will be represented. Come and join us for a closed course event friendly for the beginner and seasoned duathlete alike.', 64, 'https://chillywilly.racehawk.com/Default.aspx', true, '', 0, '2019-09-07 22:19:40', true);
INSERT INTO ournextrace.races VALUES (81, 'Sand Key OWS Series - March', '2019-03-09 00:00:00', 'Join us at beautiful Sand Key Park for Open Water races of various distances.
If you are an experienced open water swimmer, a pool swimmer looking for a new challenge, or training for a 70.3 or 140.6 - you will enjoy the challenge and the beauty of Sand Key Park. Come out and swim with some of the best swimmers in the Tampa Bay Area. ', 72, 'https://sandkeyows.racehawk.com/', true, '', 0, '2019-09-07 22:22:53', true);
INSERT INTO ournextrace.races VALUES (82, 'Sand Key OWS Series - June', '2019-06-08 00:00:00', 'Join us at beautiful Sand Key Park for Open Water races of various distances.
If you are an experienced open water swimmer, a pool swimmer looking for a new challenge, or training for a 70.3 or 140.6 - you will enjoy the challenge and the beauty of Sand Key Park. Come out and swim with some of the best swimmers in the Tampa Bay Area. ', 72, 'https://sandkeyows.racehawk.com/', true, '', 0, '2019-09-07 22:27:11', true);
INSERT INTO ournextrace.races VALUES (83, 'Sand Key OWS Series - August', '2019-08-17 00:00:00', 'Join us at beautiful Sand Key Park for Open Water races of various distances.
If you are an experienced open water swimmer, a pool swimmer looking for a new challenge, or training for a 70.3 or 140.6 - you will enjoy the challenge and the beauty of Sand Key Park. Come out and swim with some of the best swimmers in the Tampa Bay Area. ', 72, 'https://sandkeyows.racehawk.com/', true, '', 0, '2019-09-07 22:28:19', true);
INSERT INTO ournextrace.races VALUES (84, 'Escape From Fort DeSoto Triathlo', '2019-04-13 00:00:00', 'To those of you who have done the event before, welcome back! To those new to the event, you may be interested to know that the park is ranked one of the top-ten beaches in the United States; nine hundred unspoiled acres surround you. First timers, we anticipate that you will have a great first triathlon at Ft. De Soto. To all, we ask that you enjoy the surroundings and please leave the park cleaner than you found it. The Run portion of this event goes over the top of Ft De Soto itself so the sprint/international run courses are 3.4 miles and 6.8 miles. ', 64, 'https://escapetriathlon.racehawk.com/', true, '', 0, '2019-09-07 22:25:43', true);
INSERT INTO ournextrace.races VALUES (85, 'Top Gun Triathlon 2019', '2019-07-20 00:00:00', 'Welcome new and returning Top Gun Triathlon participants - 2018 marks the 19th year for this legendary local event!
The Top Gun Triathlon is traditionally one of the largest sprint triathlon in the Tampa Bay area. Register as an individual or grab some friends and take part in a 2 or 3 person relay team!', 64, 'https://topguntri.racehawk.com/', true, '', 0, '2019-09-07 22:28:01', true);
INSERT INTO ournextrace.races VALUES (86, 'The 5th Annual WOB Westchase 5k', '2019-03-02 00:00:00', 'Join us as we run within the Westchase area to support a great local charity the Special Operation Warriors Foundation.
Support a great cause by running with us! ', 73, 'https://wob5kwestchase.racehawk.com/', true, '', 0, '2019-12-01 18:00:00', true);
INSERT INTO ournextrace.races VALUES (88, 'Madeira Beach 5K Sunset Series (3 Races)', '2019-06-14 00:00:00', 'Madeira Beach is known for incredible sunsets. Each Friday evening of the Madeira Beach 5K Sunset Series, runners will take to the sand and enjoy the famous, breath-taking views. Sandy beaches/Rita''s Italian Ice/ Craft Beer/Post-race party and sunsets. All races are on the beach, yes you will have to run in the sand. ', 74, 'https://madeirabeach5k.racehawk.com/', true, '', 0, '2019-09-07 22:27:15', true);
INSERT INTO ournextrace.races VALUES (89, 'Madeira Beach 5K Sunset Series - July', '2019-07-12 00:00:00', 'Madeira Beach is known for incredible sunsets. Each Friday evening of the Madeira Beach 5K Sunset Series, runners will take to the sand and enjoy the famous, breath-taking views. Sandy beaches/Rita''s Italian Ice/ Craft Beer/Post-race party and sunsets. All races are on the beach, yes you will have to run in the sand. ', 74, 'https://madeirabeach5k.racehawk.com/', true, '', 0, '2019-12-04 18:00:00', true);
INSERT INTO ournextrace.races VALUES (90, 'Madeira Beach 5K Sunset Series - Aug', '2019-08-09 00:00:00', 'Madeira Beach is known for incredible sunsets. Each Friday evening of the Madeira Beach 5K Sunset Series, runners will take to the sand and enjoy the famous, breath-taking views. Sandy beaches/Rita''s Italian Ice/ Craft Beer/Post-race party and sunsets. All races are on the beach, yes you will have to run in the sand. ', 74, 'https://madeirabeach5k.racehawk.com/', true, '', 0, '2019-09-07 22:28:11', true);
INSERT INTO ournextrace.races VALUES (91, 'Great Clermont Triathlon Olympic Distance', '2019-03-16 00:00:00', 'Great Clermont Triathlon ', 70, 'https://runsignup.com/Race/FL/Clermont/GreatClermontTriathlon', true, '', 0, '2019-09-07 22:23:28', true);
INSERT INTO ournextrace.races VALUES (92, 'Florida Challenge Triathlon - The Intimidator', '2019-03-16 00:00:00', 'Florida''s Premier Endurance Event - Half Distance (70.3) Tri, Aqua Bike, Sprint Tri, & Open Water Swim! ', 70, 'http://sommersports.com/Events/Triathlons/Intimidator-Florida-Challenge-Triathlon', true, '', 0, '2019-09-07 22:23:44', true);
INSERT INTO ournextrace.races VALUES (93, 'Lake Minneola Sunset Triathlon, Duathlon, AquaBike & 5K ', '2019-03-30 00:00:00', 'Lake Minneola Sunset Sprint Triathlon - Race into the sunset at beautiful Lake Minneola!', 70, 'http://www.sommersports.com/Events/Triathlons/Lake-Minneola-Sunset-Sprint-Triathlon', true, '', 0, '2019-12-08 18:00:00', true);
INSERT INTO ournextrace.races VALUES (94, 'Girlz on Fire Women''s Triathlon at the World Triathlon Destination, Clermont, FL', '2019-05-11 00:00:00', 'Girlz on Fire Women''s Triathlon & Duathlon - Celebrate Mother''s Day Weekend swimming, biking and running!', 70, 'http://sommersports.com/Events/Triathlons/Girlz-on-Fire-Triathlon', true, '', 0, '2019-12-09 18:00:00', true);
INSERT INTO ournextrace.races VALUES (95, 'XC Gravel Race Series ', '2019-02-09 00:00:00', 'This is the best way to explain what is a Gravel race , With gravel races, it''s all about the experience, so there''s so much less stress and anxiety, Sure, you want to do well, but that''s entirely secondary. First and foremost, you want to just ride it and see what happens. What you''re invariably left with is an incredibly epic experience that resonates for days after the event.  ', 75, '', true, '', 0, '2019-12-10 18:00:00', true);
INSERT INTO ournextrace.races VALUES (96, 'Wildman Triathlon Festival ', '2019-03-23 00:00:00', 'Swim in beautiful Lake Louisa, at this time of year wetsuits will most likely be allowed but you can need to know how that affects you as an athlete.  You can check the current water temperature right here.  Bike on one of the most beautiful and safe courses in the State of Florida. ', 76, 'http://www.epicsportsmarketing.com/our-races/wildman-triathlon-festival', true, '', 0, '2019-09-07 22:24:05', true);
INSERT INTO ournextrace.races VALUES (98, 'Spring Fling Triathlon Festival ', '2019-05-11 00:00:00', 'Swim in beautiful Lake Louisa in Lake County, a favored location for triathlons for many years.  You can check the current water temperature right here.  Bike on an almost flat and fast course!  This venue is known for its awesome wide open asphalt roads that wind through beautiful natural landscapes.', 76, 'http://www.epicsportsmarketing.com/our-races/spring-fling-triathlon-festival', true, '', 0, '2019-09-07 22:26:43', true);
INSERT INTO ournextrace.races VALUES (99, 'Father''s Day Triathlon Festival ', '2019-06-15 00:00:00', 'Swim in beautiful Lake Louisa. ', 76, 'http://www.epicsportsmarketing.com/our-races/', true, '', 0, '2019-09-07 22:27:23', true);
INSERT INTO ournextrace.races VALUES (100, 'BelieveStrong Triathlon', '2019-08-24 00:00:00', 'Swim in beautiful Lake Louisa State park. This race is held in remembrance of Local triathlete Roy McConnell who was tragically killed in a car accident with his sons.', 76, 'http://www.epicsportsmarketing.com/our-races/believe-strong-triathlon-festival', true, '', 0, '2019-09-07 22:28:27', true);
INSERT INTO ournextrace.races VALUES (101, 'Epic Triathlon Festival', '2019-09-21 00:00:00', 'Swim in beautiful Lake Louisa State park. This race is held in remembrance of Local triathlete Roy McConnell who was tragically killed in a car accident with his sons.', 76, 'http://www.epicsportsmarketing.com/our-races/believe-strong-triathlon-festival-3gdpg', true, '', 0, '2019-09-07 22:28:39', true);
INSERT INTO ournextrace.races VALUES (102, 'Gran Fondo Florida', '2019-03-24 00:00:00', 'It travels along rural rolling hills, past horse farms and crystal clear springs. Briefly going through Withlacoochee State Forest and the hills surrounding Brooksville, Florida.', 77, 'https://www.granfondonationalseries.com/gran-fondo-florida/', true, '', 0, '2019-09-07 22:24:22', true);
INSERT INTO ournextrace.races VALUES (103, 'Lycra & Lace Women''s Triathlon', '2019-10-05 00:00:00', 'Lycra & Lace Women''s Triathlon', 64, 'racehawk.com', true, '', 0, '2019-09-07 22:28:50', true);
INSERT INTO ournextrace.races VALUES (104, 'Youth Dash & Splash', '2019-06-01 00:00:00', 'Youth Dash & Splash', 64, 'racehawk.com', true, '', 0, '2019-12-19 18:00:00', true);
INSERT INTO ournextrace.races VALUES (105, 'Lake Apopka Scenic Trail 30K Run', '2019-02-23 00:00:00', 'The Lake Apopka Loop Trail covers more than 20 miles, providing hiking and biking opportunities along and in close proximity to the Lake Apopka shoreline. Currently it is just a point to point trail, but is expected to circumnavigate Lake Apopka in the future.', 78, 'http://www.sommersports.com/Events/Running/Lake-Apopka-Scenic-Trail-30K', true, '', 0, '2019-12-20 18:00:00', true);
INSERT INTO ournextrace.races VALUES (106, 'Xterra Claw 5M & 10M Trail Run', '2019-05-05 00:00:00', '5M course will be a nice run through the park using a entirely different set of trails than all other races at Alafia. The 10M course includes the 5M course plus adds another 5M in a section of the park that is not open to the public - it should be a challenging and fun course and worthy of the XTERRA name. ', 41, 'https://www.eventbrite.com/e/the-claw-10-5-mile-adventure-run-registration-49909089430', true, '', 0, '2019-12-21 18:00:00', true);
INSERT INTO ournextrace.races VALUES (107, 'MOON OVER CROOM', '2019-06-15 00:00:00', 'The Moon Over Croom is brand new trail run that will take in the evening at Croom Park in Brooksville. Experience Croom like you never had before by running in the dark. The course will use B-C Loop and the C-Loop making it a seven mile loop.

There will be great t-shirts, food, and an experience you won''t forget so you don''t want to miss this one. For the 2019 race, there is a limit of 250 runners. ', 79, 'http://croomzoom.com/moon/Index.htm', true, '', 0, '2019-09-07 22:27:31', true);
INSERT INTO ournextrace.races VALUES (108, 'MCM - Marine Corp Marathon', '2019-10-27 00:00:00', 'Best for Beginners. Best Organized. Marathon of the Monuments. The will-do, must-do, can-do marathon.', 80, 'http://www.marinemarathon.com/events/marathon', true, '', 0, '2019-09-07 22:28:57', true);
INSERT INTO ournextrace.races VALUES (127, 'Mt. Dora Half Marathon', '2019-12-22 00:00:00', 'Hilly Race. 5K on Saturday and Sunday is the half', 17, 'http://www.mountdorahalfmarathon.com/', true, '', 0, '2019-10-01 22:57:01', true);
INSERT INTO ournextrace.races VALUES (122, 'Best Damn Race (BDR) Savannah', '2019-02-16 00:00:00', '', 90, 'https://savannah.bestdamnrace.com/', true, '', 0, '2019-09-07 22:21:39', true);
INSERT INTO ournextrace.races VALUES (133, 'Florida Shamrock Halfathon & 5K Race', '2020-03-15 00:00:00', 'Get your green on and join us in celebrating the arrival of spring during our 10th Annual Florida Shamrock Halfathon & 5K Race (formerly Florida Beach Halfathon and 5K), at Fort De Soto Park, located near St. Petersburg on Florida''s beautiful west coast at the mouth of Tampa Bay.', 64, 'https://www.active.com/st-petersburg-fl/running/distance-running-races/10th-annual-florida-shamrock-halfathon-and-5k-race-2019?int=72-3-A8', true, '', 0, '2019-10-01 23:24:24', true);
INSERT INTO ournextrace.races VALUES (134, 'St. Anthony''s Triathlon', '2020-04-25 00:00:00', 'St. Petersburg Fl - Vinoy Park', 14, 'https://baycare.org/satriathlon', true, '', 0, '2019-10-01 23:49:08', true);
INSERT INTO ournextrace.races VALUES (135, 'Best Damn Race (Safety Harbor)', '2020-02-01 00:00:00', 'Located in Saftey Harbor. Two day event. Half on Sunday', 25, 'https://safetyharbor.bestdamnrace.com/', true, '', 0, '2019-10-01 23:51:10', true);
INSERT INTO ournextrace.races VALUES (146, 'Zooma Florida Half Marathon', '2019-10-19 00:00:00', 'Zooma Florida was voted one of the top 20 half marathons AND top 20 for beautiful, on-course scenery', 2, 'http://zoomarun.com/race/florida/', true, '', 0, '2019-10-02 00:38:33', true);
INSERT INTO ournextrace.races VALUES (124, 'Divas', '2019-05-05 00:00:00', 'Why pay for a tour of the city''s best areas when you can do it on your feet! This course starts right on Ocean Blvd. heading south towards Atlantic Beach, one of the Grand Strand''s most historical areas. ', 91, 'https://www.runlikeadiva.com/Events/Divas__Half_Marathon___5K_-_North_Myrtle_Beach.htm', true, '', 0, '2020-01-08 18:00:00', true);
INSERT INTO ournextrace.races VALUES (136, 'Best Damn Race (BDR) Savannah', '2020-02-15 00:00:00', '', 90, 'https://savannah.bestdamnrace.com/', true, '', 0, '2019-10-01 23:51:44', true);
INSERT INTO ournextrace.races VALUES (150, 'Tampa Bay Times Turkey Trot', '2019-11-28 00:00:00', 'Clearwater High School', 10, 'https://www.tampabay.com/marketing/turkey-trot/', true, '', 0, '2019-10-02 00:58:13', true);
INSERT INTO ournextrace.races VALUES (13, 'Best Damn Race (Safety Harbor)', '2019-02-02 00:00:00', 'Located in Saftey Harbor', 0, 'https://safetyharbor.bestdamnrace.com/', true, '', 0, '2019-10-01 23:50:28', true);
INSERT INTO ournextrace.races VALUES (110, 'Ironman Florida', '2019-11-02 00:00:00', 'he 2019 IRONMAN Florida will offer 40 qualifying slots to the 2020 IRONMAN World Championship in Kona, Hawaii.

Originally from: http://www.ironman.com/triathlon/events/americas/ironman/florida.aspx#ixzz5db9U0ncH', 7, 'http://www.ironman.com/triathlon/events/americas/ironman/florida.aspx', true, '', 0, '2019-09-07 22:29:06', true);
INSERT INTO ournextrace.races VALUES (111, 'IRONMAN 70.3 FLORIDA', '2019-04-14 00:00:00', '', 28, 'http://www.ironman.com/triathlon/events/americas/ironman-70.3/florida.aspx', true, '', 0, '2019-09-07 22:25:49', true);
INSERT INTO ournextrace.races VALUES (112, 'IRONMAN 70.3 GULF COAST', '2019-05-11 00:00:00', 'Formally known as the Gulf Coast Triathlon. We are proud to continue the long rich history', 7, 'http://www.ironman.com/triathlon/events/americas/ironman-70.3/gulf-coast', true, '', 0, '2019-09-07 22:26:53', true);
INSERT INTO ournextrace.races VALUES (113, 'IRONMAN 70.3 Steelhead Event Schedule', '2019-06-30 00:00:00', '', 82, 'http://www.ironman.com/triathlon/events/americas/ironman-70.3/steelhead.aspx', true, '', 0, '2019-09-07 22:27:55', true);
INSERT INTO ournextrace.races VALUES (114, 'Memorial Hermann IRONMAN North American Championship Texas', '2019-04-27 00:00:00', 'Memorial Hermann IRONMAN Texas will showcase the region’s signature
features. During race weekend, take time to experience all The Woodlands has
to offer; from dining to shopping, I am sure this area will not disappoint.', 83, 'http://www.ironman.com/triathlon/events/americas/ironman/texas.aspx', true, '', 0, '2019-09-07 22:26:14', true);
INSERT INTO ournextrace.races VALUES (115, 'IRONMAN 70.3 Virginia ', '2019-05-05 00:00:00', '', 84, 'http://www.ironman.com/triathlon/events/americas/ironman-70.3/virginia/race-info/event-schedule.aspx', true, '', 0, '2019-09-07 22:26:32', true);
INSERT INTO ournextrace.races VALUES (116, 'Ironman Wisconsin', '2019-09-08 00:00:00', 'Athletes will feel the roar of the crowd as the cannon signals the start of the race in the waters of Lake Monona. Then set off on the legendary two-loop bike course ridden in the beautiful rural landscape that can only be Wisconsin. The crowds will gather in Verona, Mt. Horeb and other towns to cheer the athletes on. The run will give athletes a great tour of Downtown Madison and the UW Campus as the two-loop course showcases many famous landmarks including the Capitol, State St, Camp Randall, and Observatory Hill. ', 85, 'http://www.ironman.com/triathlon/events/americas/ironman/wisconsin.aspx', true, '', 0, '2019-09-07 22:28:31', true);
INSERT INTO ournextrace.races VALUES (117, 'Rev 3 - Westfields Triathlon', '2019-04-28 00:00:00', 'This Westfields Triathlon marks the kickoff to the triathlon season in the DC Metro area.  Taking place at Cub Run RECenter in Chantilly, VA this sprint triathlon is a great way to dust off the cobwebs and get ready for a new season of swimming, biking, and running.  This event is also great for first timers who want to explore the sport of triathlon without all the pressure.', 86, 'http://rev3tri.com/westfields/', true, '', 0, '2020-01-01 18:00:00', true);
INSERT INTO ournextrace.races VALUES (118, 'IRONMAN 70.3 COSTA RICA ', '2019-06-23 00:00:00', 'Imagine a magical place where nature surrounds you; an alluring concentration of beauty, rainforests, beaches, landscapes, microclimates and biodiversity. One of the happiest places in the globe, and the world’s capital of hummingbirds.

Originally from: http://www.ironman.com/triathlon/events/americas/ironman-70.3/costa-rica.aspx#ixzz5e4HxeXod', 87, 'http://www.ironman.com/triathlon/events/americas/ironman-70.3/costa-rica.aspx', true, '', 0, '2019-09-07 22:27:50', true);
INSERT INTO ournextrace.races VALUES (119, 'DONNA Marathon', '2019-02-10 00:00:00', 'NEW In 2019, DONNA Marathon Weekend will start and finish in the heart of Neptune Beach and Atlantic Beach, Florida. Known by locals as the Beaches Town Center, this oceanfront destination twelve miles east of downtown Jacksonville offers a wealth of choices to shop, dine, relax and now race!', 88, 'https://breastcancermarathon.com/', true, '', 0, '2019-09-07 22:21:28', true);
INSERT INTO ournextrace.races VALUES (120, 'Shamrock Classic 5k', '2019-03-16 00:00:00', 'The Shamrock Classic 10k/5k/1 Mile Fun Run course begins right outside of the race''s title sponsor O''Brien''s Irish Pub on S Kings Ave and Lumsden Road. The course is a flat, fast, 1.5 miles out and back distance heading South towards Bloomingdale on S Kings Ave. ', 89, 'http://www.brandonrunning.com/shamrock-classic-10k5k1m-race-information.html', true, '', 0, '2020-01-04 18:00:00', true);
INSERT INTO ournextrace.races VALUES (121, 'Shamrock Classic 10k', '2019-02-16 00:00:00', 'The Shamrock Classic 10k/5k/1 Mile Fun Run course begins right outside of the race''s title sponsor O''Brien''s Irish Pub on S Kings Ave and Lumsden Road. The course is a flat, fast, 1.5 miles out and back distance heading South towards Bloomingdale on S Kings Ave. ', 89, 'http://www.brandonrunning.com/shamrock-classic-10k5k1m-race-information.html', true, '', 0, '2020-01-05 18:00:00', true);
INSERT INTO ournextrace.races VALUES (123, 'Best Damn Race Orlando (BDR)', '2019-03-02 00:00:00', 'is a running series created for runners by runners. Our goal is to provide a big race experience at a local race price. It doesn’t matter if you are an elite runner, first timer, walker, or using a baby jogger, we want you to have the best DAMN race experience.', 58, 'https://runsignup.com/Race/FL/Orlando/BestDamnRaceORL?raceRefCode=Atk20Y0h', true, '', 0, '2019-09-07 22:22:14', true);
INSERT INTO ournextrace.races VALUES (153, 'Aquathlon Nationals', '2019-11-09 00:00:00', 'Aquathlon Nationals: 1000m swim, 5k run', 101, 'https://www.miamimanhalfiron.com/usat-long-course-championship', false, '', 0, '2019-10-02 16:49:24', false);
INSERT INTO ournextrace.races VALUES (154, 'Test', '2019-10-03 00:00:00', 'Test', 0, 'test', false, '', 0, '2019-10-03 00:07:13', false);
INSERT INTO ournextrace.races VALUES (125, 'Challange Daytona', '2019-12-15 00:00:00', 'Challenge this! Swim, bike, and run at Daytona International Speedway, the iconic “World Center of Racing,” during the CHALLENGEDAYTONA festival weekend. December 15, 2019, it’s on!', 4, 'https://challenge-daytona.com/races/middle-distance-2/', true, '', 0, '2019-09-07 22:29:21', true);
INSERT INTO ournextrace.races VALUES (126, '20k Relay Race: Destination St. Petersburg FL', '2019-06-15 00:00:00', ' The chip-timed race will start at 8am in the beautiful Downtown St. Petersburg.', 92, 'https://www.active.com/st-petersburg-fl/running/distance-running-races/20k-relay-race-destination-st-petersburg-fl-2019', true, '', 0, '2020-01-10 18:00:00', true);
INSERT INTO ournextrace.races VALUES (128, 'Tradewinds Trilogy Round #3', '2019-10-13 00:00:00', 'TRADEWINDS TRILOGY SPRINT TRIATHLONS & DUATHLONS', 94, 'https://www.tradewindstrilogy.com', true, '', 0, '2019-10-01 23:06:48', false);
INSERT INTO ournextrace.races VALUES (129, 'City island Sarasota triathlon', '2019-11-17 00:00:00', 'The Longboat Key Triathlon on November 17th is my race, the start and finish are from City Island by Mote Marine Aquarium, and the route goes into Longboat Key. You will go over the New Pass bridge on the bike and over and under on the run - the run course is epic in my opinion!
Sarasota Police and Longboat key Police will be watching the roads for you. - Thierry', 95, 'https://runsignup.com/Race/FL/Sarasota/LBKSRQtriathlon', true, '', 0, '2019-10-01 23:14:43', false);
INSERT INTO ournextrace.races VALUES (130, 'Halloween Distance Classic', '2019-10-27 00:00:00', 'Costumes encouraged! Create unique costumes in the spirit of this festive holiday, but ones that will not adversely affect your performance. Show off your creativity by entering our costume costume and win some more awards!', 64, 'http://www.floridahalloweenhalfathon.com/', true, '', 0, '2019-10-01 23:17:40', false);
INSERT INTO ournextrace.races VALUES (131, 'Florida Holiday Halfathon & 10K', '2019-12-08 00:00:00', 'We invite you to join the 18th Annual Florida Holiday Halfathon & 10K, our point-to-point course, which is fast, flat, scenic and aesthetically varied: just one small bridge (Park Boulevard Bridge, four miles into the course) and two overpasses, with the rest of the course 10 – 25 feet above sea level.', 96, 'http://www.floridaholidayhalfathon.com/', true, '', 0, '2019-10-01 23:21:37', false);
INSERT INTO ournextrace.races VALUES (132, 'St. Petersburg Distance Classic', '2020-02-09 00:00:00', 'LL four race courses start out exactly the same for the first 2 miles – heading north into Snell Isle. While 5K participants return towards the finish line, all other participants will head north and around Coffee Pot Bayou before returning back towards North Shore Park.

The Halfathon and Marathon head south along the waterfront, through our bustling downtown and onto Central Avenue which features a dynamic mixture of the best local shops found anywhere. Watch for an abundance of huge murals on Central Avenue’s building walls, as St. Petersburg is truly a well-know haven for artists of all types.', 33, 'http://stpetersburgdistanceclassic.com/', true, '', 0, '2019-10-01 23:23:09', false);
INSERT INTO ournextrace.races VALUES (137, 'Best Damn Race Orlando (BDR)', '2020-02-29 00:00:00', 'is a running series created for runners by runners. Our goal is to provide a big race experience at a local race price. It doesn’t matter if you are an elite runner, first timer, walker, or using a baby jogger, we want you to have the best DAMN race experience.', 58, 'https://runsignup.com/Race/FL/Orlando/BestDamnRaceORL?raceRefCode=Atk20Y0h', true, '', 0, '2019-10-01 23:52:09', true);
INSERT INTO ournextrace.races VALUES (138, 'Best Damn Race (New Orleans) BDR', '2020-03-22 00:00:00', 'is a running series created for runners by runners. Our goal is to provide a big race experience at a local race price. It doesn’t matter if you are an elite runner, first timer, walker, or using a baby jogger, we want you to have the best DAMN race experience.', 97, 'https://neworleans.bestdamnrace.com/about/', true, '', 0, '2019-10-01 23:56:45', false);
INSERT INTO ournextrace.races VALUES (139, 'Mount Dora Bicycle Festival', '2019-10-03 00:00:00', 'Oct 3-Oct 6 - Mount Dora has been hosting bicyclists for more than 40 years and attracts a thousand bicyclists. Mount Dora is another charming small town. It keeps the visitors coming with a series of big festivals from fall to spring.', 0, 'https://www.mountdorabicyclefestival.com/', false, '', 0, '2019-10-02 00:02:18', false);
INSERT INTO ournextrace.races VALUES (140, 'Longboat Key Triathlon (Sprint and Olympic) ', '2019-12-01 00:00:00', 'The Fall 2019 Longboat Key Race Series Date Is Moving to December 1st, 2019
We have expanded our participant availability and added our new 5K and 10K Hollywood Nights theme races. The construction at Longboat Key Club has been completed and we now have an abundance of parking on-site at the resort to accommodate more participation from our athletes. ', 0, 'https://www.lbktriathlon.com/', false, '', 0, '2019-10-02 00:05:18', false);
INSERT INTO ournextrace.races VALUES (141, 'Excalibur 10 Miler & Relay ', '2020-03-14 00:00:00', 'We are extremely excited to announce our new Excalibur Distance Festival coming March 2020 at Viera Regional Park in Melbourne, FL. The Excalibur Distance Festival will include three events held over the weekend with 4 Challenge options available. You do not need to select a challenge to participate in the fun. Keep scrolling to see the challenge and individual finisher medals below.', 0, 'https://excaliburrun.com/', true, '', 0, '2019-10-02 00:10:20', false);
INSERT INTO ournextrace.races VALUES (142, 'Metro Diner Sarasota Music Half Marathon', '2020-02-02 00:00:00', '13.1 and 6.2 mile moving party with thousands of your buddies: Oh yeah we added a 5K this year!

Bands  - Rock to the Music
Run St. Armand''s Circle and over the Rignling Bridge
Gourmet post-race brunch provided by Metro Diner
Cool Bling
Beer Mile
Beautiful neighborhoods and lawn parties
Wicked cool participation Medal and T-shirts
Rockin after-party with live music, massages, beer garden and tons of fun!', 21, 'https://www.eventbrite.com/e/2020-metro-diner-sarasota-music-half-marathon-rockin-10k-5k-registration-55368799570', true, '', 0, '2019-10-02 00:09:43', false);
INSERT INTO ournextrace.races VALUES (143, 'Florida Xtreme Triathlon', '2019-11-15 00:00:00', 'A 3-day, 3-stage, 300+ mile, coast to coast triathlon across Florida. This is a point to point event. Course support will be provided; however, each participant is encouraged to bring two crew members with them for additional support.', 0, 'http://floridaxtremetriathlon.com', false, '', 0, '2019-10-02 00:11:31', false);
INSERT INTO ournextrace.races VALUES (144, '3BRIDGERACE', '2019-10-26 00:00:00', 'There’s so much to get your adrenaline pumping for this race – a beautiful course, new kids dash, swag bag, VIP parties, pre and post park activities, entertainment and more! Most importantly it’s all for a great opportunity to join Team CFY in our mission to provide the opportunity for children from all backgrounds to learn and play together and to build character through sports.', 19, 'https://the3bridgerace.com/', true, '', 0, '2019-10-02 00:52:34', false);
INSERT INTO ournextrace.races VALUES (145, 'Cocoa Beach Half Marathon', '2019-10-20 00:00:00', 'Run by the sea and through the most storied beach history on the Space Coast as you head up coastal A1A from Patrick Air Force Base and into Cocoa Beach. From there, you will continue up A1A passing by our title sponsor’s World Famous Ron Jon Surf Shop and looping through a tree-lined neighborhood before entering an access where you will begin your low-tide, 2.9 mile run on the flat and hard-packed sands of Cocoa Beach.', 98, 'http://cocoabeachhalfmarathon.com/', true, '', 0, '2019-10-02 00:36:52', false);
INSERT INTO ournextrace.races VALUES (147, 'Divas', '2020-04-05 00:00:00', 'Why pay for a tour of the city''s best areas when you can do it on your feet! This course starts right on Ocean Blvd. heading south towards Atlantic Beach, one of the Grand Strand''s most historical areas. ', 91, 'https://www.runlikeadiva.com/Events/Divas__Half_Marathon___5K_-_North_Myrtle_Beach.htm', true, '', 0, '2019-10-02 00:42:32', true);
INSERT INTO ournextrace.races VALUES (148, 'Publix Florida Marathon & 1/2 Marathon', '2020-02-02 00:00:00', 'One of America''s Top 10 Bucket List Waterfront Races, says Runners World Magazine. The Publix Florida Marathon & 1/2 Marathon begins in downtown Melbourne and traverses along scenic US1 and the Indian River offering great water views and two bridge crossings for half-marathoners with four for the full marathon runners.  The event has water stops each mile of the course and will feature at least 20 musical acts along the route with a post-race concert providing beer, pizza and more to runners. The 1/2 Marathon Relay offers two runners the chance to work together on a 6.55 mile tag-team run with each receiving a finishers medal.', 99, 'http://thefloridamarathon.com/registration/', true, '', 0, '2019-10-02 00:44:49', false);
INSERT INTO ournextrace.races VALUES (149, 'Getaway: St. Petersburg', '2019-11-03 00:00:00', 'Sun, Fun, Run! Escape to the Getaway St. Petersburg! This experience is designed for the entire family. No matter what your age, you’re sure to have a good time. The St. Pete event will feature multiple distances, and a fun run designed especially for the kids.', 100, 'https://www.getaway5k.com/races/stpete-fl/', true, '', 0, '2019-10-02 00:55:48', false);
INSERT INTO ournextrace.races VALUES (151, 'DONNA Marathon', '2020-02-09 00:00:00', 'NEW In 2019, DONNA Marathon Weekend will start and finish in the heart of Neptune Beach and Atlantic Beach, Florida. Known by locals as the Beaches Town Center, this oceanfront destination twelve miles east of downtown Jacksonville offers a wealth of choices to shop, dine, relax and now race!', 88, 'https://breastcancermarathon.com/', true, '', 0, '2019-10-02 00:58:38', true);
INSERT INTO ournextrace.races VALUES (152, 'Miami Man International and Half Triathlon , Duathlon and Aquabike', '2019-11-10 00:00:00', 'USA Triathlon and Multirace LLC are partnering to produce to bring you the USA Triathlon Multisport National Championships Festival! The festival, hosted as part of the annual Miami Man Triathlon, will bring together 5 USA Triathlon National Championships on November 9-10, 2019.', 101, 'https://www.miamimanhalfiron.com/', false, '', 0, '2019-10-02 16:46:25', false);