
INSERT INTO ournextrace.race_type(id,name,description, short_desc) VALUES (1,'Full Marathon 26.2','26.2 Miles', 'Marathon');
INSERT INTO ournextrace.race_type(id,name,description, short_desc) VALUES (10,'Half Marathon 13.1','13.1 Miles', 'Half Marathon');
INSERT INTO ournextrace.race_type(id,name,description, short_desc) VALUES (20,'15K','15K Run', '15K');
INSERT INTO ournextrace.race_type(id,name,description, short_desc) VALUES (30,'10K','6.2 Mile Run', '10K');
INSERT INTO ournextrace.race_type(id,name,description, short_desc) VALUES (40,'5K','3.1 Mile Run', '5K');
INSERT INTO ournextrace.race_type(id,name,description, short_desc) VALUES (50,'1 Mile','1 Mile Run', '1 Mile');
INSERT INTO ournextrace.race_type(id,name,description, short_desc) VALUES (60,'Ultra','26.2 miles or greater', 'Ultra');
INSERT INTO ournextrace.race_type(id,name,description, short_desc) VALUES (70,'Trail Run','Some Long Trail Run', 'Trail Run');
INSERT INTO ournextrace.race_type(id,name,description, short_desc) VALUES (80,'Full Ironman (140.6)','2.4 Mile Swim, 112 Mile Bike, 26.2 Run', 'Full IM');
INSERT INTO ournextrace.race_type(id,name,description, short_desc) VALUES (90,'Half Ironman (70.3)','1.2 Mile Swim, 56 Mile Bike, 13.1 Run', '70.3');
INSERT INTO ournextrace.race_type(id,name,description, short_desc) VALUES (100,'Olympic Triathlon','1.5k swim, 40k (26 Mile) bike, 10k run', 'Olympic');
INSERT INTO ournextrace.race_type(id,name,description, short_desc) VALUES (110,'Sprint Triathlon','400 yard+ swim, 10 Mile bike, 5k run', 'Sprint');
INSERT INTO ournextrace.race_type(id,name,description, short_desc) VALUES (120,'Super Sprint Triathlon','200 yard+ swim, < 10 Mile bike, < 5k run', 'Super');
INSERT INTO ournextrace.race_type(id,name,description, short_desc) VALUES (130,'OWS - Open Water Swim','OWS - Open Water Swim', 'OWS');
INSERT INTO ournextrace.race_type(id,name,description, short_desc) VALUES (140,'Aqua Bike','Swim and Bike', 'Aqua Bike');
INSERT INTO ournextrace.race_type(id,name,description, short_desc) VALUES (150,'Duathlon','Run, Bike, Run', 'Duo');
INSERT INTO ournextrace.race_type(id,name,description, short_desc) VALUES (160,'Swim Meet','Masters Swim Meet', 'Swim Meet');
INSERT INTO ournextrace.race_type(id,name,description, short_desc) VALUES (170,'8K','8k ~ 5 Mile Run', '8K');
INSERT INTO ournextrace.race_type(id,name,description, short_desc) VALUES (180,'5 Miler','5 Mile Run', '5 Miler');
INSERT INTO ournextrace.race_type(id,name,description, short_desc) VALUES (190,'10 Miler','10 Mile Run', '10 Miler');
INSERT INTO ournextrace.race_type(id,name,description, short_desc) VALUES (200,'50 Miler','50 Mile Run', '50 Miler');
INSERT INTO ournextrace.race_type(id,name,description, short_desc) VALUES (210,'50K','50 Kilometers (31 Miles)', '50K');
INSERT INTO ournextrace.race_type(id,name,description, short_desc) VALUES (220,'16 Miler','16 Mile Run (Trail)', '16 Miler');
INSERT INTO ournextrace.race_type(id,name,description, short_desc) VALUES (230,'12K','12K (7.54 Miles)', '12K');
INSERT INTO ournextrace.race_type(id,name,description, short_desc) VALUES (240,'Biathlon - Sprint','Run 5K Bike 10 Miles', 'Biathon');
INSERT INTO ournextrace.race_type(id,name,description, short_desc) VALUES (250,'Gravel Race - Cycling','Grave Race - Cycling on Trails', 'Gravel');
INSERT INTO ournextrace.race_type(id,name,description, short_desc) VALUES (260,'Gran Fondo - Cycling','Only the timed segments count', 'Fondo');
INSERT INTO ournextrace.race_type(id,name,description, short_desc) VALUES (280,'20K','10K Twice', '20K');
